services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7709800436:AAG9zdInNqWmU-TW7IuzioHhy_McWnqLw0w
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        value: sqlite:///users.db
    healthCheckPath: /
    autoDeploy: true